name: RadioExtended-ci

on:
  push:
    # branches: [ "master" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        bepinex-version: [5, 6]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Checkout libcs2
        uses: actions/checkout@v4
        with:
          repository: AlphaGaming7780/libcs2
          token: ${{ secrets.GH_PAT }}
          path: libcs2/
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build (BepInEx ${{ matrix.bepinex-version }})
        run: make package-unix BEPINEX_VERSION=${{ matrix.bepinex-version }}
      - name: Coping All the default elements
        run: |
          mkdir -p  ${{ github.workspace }}/dist/resources/;
          cp -a ${{ github.workspace }}/resources/. ${{ github.workspace }}/dist/resources/
          mv ${{ github.workspace }}/dist ${{ github.workspace }}/${{ github.event.repository.name }}
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'zip'
          filename: "${{ github.event.repository.name }}-${{ github.ref_name }}_BepInEx-${{ matrix.bepinex-version }}.zip"
          path: "${{ github.event.repository.name }}"
      # - name: Upload Artifact (BepInEx ${{ matrix.bepinex-version }})
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: built-code-${{ matrix.bepinex-version }}
      #     path: dist/*.dll
      - name: Upload Artifact (Zip Release BepInEx ${{ matrix.bepinex-version }})
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}-${{ github.ref_name }}_BepInEx-${{ matrix.bepinex-version }}
          path: ${{ github.event.repository.name }}-${{ github.ref_name }}_BepInEx-${{ matrix.bepinex-version }}.zip

  # publish:
  #   needs: build
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source
  #       uses: actions/checkout@v3
  #     - name: Download built artifact
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: built-code-5
  #         path: dist/
  #     - name: Debug
  #       run: ls && ls dist/
  #     - name: Download tcli
  #       run: |
  #         curl -L https://github.com/thunderstore-io/thunderstore-cli/releases/download/0.2.1/tcli-0.2.1-linux-x64.tar.gz -o tcli.tar.gz
  #         tar -xzf tcli.tar.gz
  #     - name: Publish with tcli
  #       run: ./tcli-0.2.1-linux-x64/tcli publish --token=${{ secrets.TS_TOKEN }}

  Release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Download Zip artifact
        uses: actions/download-artifact@v3
        with:
          path: zip/
      - name: Create Release
        uses: ncipollo/release-action@v1.13.0
        with:
          tag: ${{ github.ref_name }}
          allowUpdates: true
          removeArtifacts: true
          artifacts: "${{ github.event.repository.name }}-${{ github.ref_name }}_BepInEx-5,${{ github.event.repository.name }}-${{ github.ref_name }}_BepInEx-6"
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}


